#!/usr/bin/env python3
"""Small LAN control panel for the AI Benchmark command line runner."""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import threading
import tomllib
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SUITES = ("core", "coding-agent", "rag", "vision", "image", "speech", "music", "web")


def results_root() -> Path:
    configured = os.environ.get("BENCH_RESULTS_DIR")
    if configured:
        return Path(configured).expanduser()
    return Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local")) / "ai-benchmark"


def load_catalog() -> list[dict[str, Any]]:
    return tomllib.loads((ROOT / "config/models.toml").read_text(encoding="utf-8")).get("models", [])


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return str(value)


def selected_catalog(models: set[str]) -> Path:
    destination = results_root() / "ui-selections" / f"models-{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}.toml"
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Per-run selection generated by the benchmark web interface.", ""]
    for row in load_catalog():
        lines.append("[[models]]")
        for key, value in row.items():
            if key == "enabled":
                value = bool(value) and row.get("model") in models
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination


def json_file(path: Path, fallback: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return fallback


def run_directories() -> list[Path]:
    root = results_root() / "runs"
    return sorted((p for p in root.glob("*/*") if (p / "state.json").is_file()), key=lambda p: p.stat().st_mtime, reverse=True)


def run_summary(directory: Path) -> dict[str, Any]:
    state = json_file(directory / "state.json", {})
    return {"id": directory.name, "machine": directory.parent.name, "state": state}


def tail(path: Path, size: int = 30_000) -> str:
    try:
        with path.open("rb") as handle:
            handle.seek(0, 2)
            handle.seek(max(0, handle.tell() - size))
            return handle.read().decode("utf-8", errors="replace")
    except OSError:
        return "No log is available yet."


PAGE = r"""<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Benchmark</title><style>
body{max-width:1100px;margin:32px auto;padding:0 18px;background:#101827;color:#e6edf7;font:16px system-ui,sans-serif}h1{margin-bottom:4px}section{background:#182235;border:1px solid #2c3b55;border-radius:10px;padding:18px;margin:18px 0}button{background:#52c78b;border:0;border-radius:6px;padding:10px 14px;font-weight:700;cursor:pointer}button:disabled{opacity:.5}label{display:block;margin:7px 0}.models{columns:2;max-height:460px;overflow:auto}.muted{color:#aebbd1}pre{background:#0b1220;padding:12px;overflow:auto;max-height:360px;white-space:pre-wrap}#message{font-weight:600}</style>
<h1>AI Benchmark</h1><p class="muted">LAN control panel. Starting a run may download selected models.</p>
<section><h2>Start a run</h2><div id="machine" class="muted">Loading machine scan…</div><h3>Suites</h3><div id="suites"></div><h3>Eligible models</h3><div id="models" class="models"></div><p>Profile: <select id="profile"><option value="quick">Quick</option><option value="standard" selected>Standard</option><option value="full">Full</option></select></p><button id="start">Start selected benchmark</button> <span id="message"></span></section>
<section><h2>Runs</h2><div id="runs" class="muted">Loading…</div></section><section><h2>Log</h2><pre id="log">Select a run to view its log.</pre></section>
<script>
let catalog=[],scan={}; const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function get(url){let r=await fetch(url);if(!r.ok)throw Error(await r.text());return r.json()}
function choices(){return [...document.querySelectorAll('input[name="model"]:checked')].map(x=>x.value)}
async function load(){let d=await get('/api/overview');catalog=d.catalog;scan=d.scan||{};document.querySelector('#machine').textContent=`RAM available: ${scan.available_ram_gib??'?'} GiB · VRAM available: ${scan.available_vram_gib??'?'} GiB · model storage free: ${scan.ollama_models_storage?.free_gib??'?'} GiB`;
document.querySelector('#suites').innerHTML=d.suites.map((s,i)=>`<label><input type="checkbox" name="suite" value="${s}" ${i===0?'checked':''}> ${s}</label>`).join('');
let eligible=new Map((scan.models||[]).filter(x=>x.allowed).map(x=>[x.model,x]));document.querySelector('#models').innerHTML=catalog.filter(m=>eligible.has(m.model)).map(m=>{let r=eligible.get(m.model);return `<label><input type="checkbox" name="model" value="${esc(m.model)}"> <b>${esc(m.model)}</b> <span class="muted">(${r.eligibility}; min. ${r.requirements.ram_gib} GiB RAM, ${r.requirements.vram_gib} GiB VRAM, ${r.requirements.free_disk_gib} GiB disk)</span></label>`}).join('')||'No eligible models. Run a machine scan first.'; await runs()}
async function runs(){let d=await get('/api/runs');document.querySelector('#runs').innerHTML=d.length?d.map(r=>{let p=r.state.progress||{};return `<p><button onclick="showLog('${r.id}')">Log</button> <b>${esc(r.id)}</b> — ${esc(r.state.status||'unknown')} — ${p.completed||0}/${p.total||0} (${p.percent||0}%)</p>`}).join(''):'No runs yet.'}
async function showLog(id){document.querySelector('#log').textContent=(await get('/api/log/'+encodeURIComponent(id))).log}
document.querySelector('#start').onclick=async()=>{let models=choices(),suites=[...document.querySelectorAll('input[name="suite"]:checked')].map(x=>x.value),message=document.querySelector('#message');if(!models.length||!suites.length){message.textContent='Choose at least one suite and one model.';return}if(!confirm(`Start ${suites.join(', ')} with ${models.length} model(s)? Missing models may be downloaded.`))return;message.textContent='Starting preflight…';try{let r=await fetch('/api/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({models,suites,profile:document.querySelector('#profile').value})});let d=await r.json();if(!r.ok)throw Error(d.error);message.textContent=d.message;setTimeout(runs,1500)}catch(e){message.textContent=e.message}}
load().catch(e=>document.body.insertAdjacentHTML('beforeend','<pre>'+esc(e.message)+'</pre>'));setInterval(runs,5000)
</script></html>"""


class App(BaseHTTPRequestHandler):
    server_version = "AIBenchmarkUI/1.0"

    def send_json(self, data: Any, status: int = 200) -> None:
        encoded = json.dumps(data).encode("utf-8")
        self.send_response(status); self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded))); self.end_headers(); self.wfile.write(encoded)

    def do_GET(self) -> None:
        if self.path == "/":
            encoded = PAGE.encode("utf-8"); self.send_response(200); self.send_header("Content-Type", "text/html; charset=utf-8"); self.send_header("Content-Length", str(len(encoded))); self.end_headers(); self.wfile.write(encoded); return
        if self.path == "/api/overview":
            scans = sorted((results_root() / "scans").glob("*/latest.json"), key=lambda p: p.stat().st_mtime, reverse=True)
            self.send_json({"catalog": load_catalog(), "suites": SUITES, "scan": json_file(scans[0], {}) if scans else {}}); return
        if self.path == "/api/runs": self.send_json([run_summary(p) for p in run_directories()[:30]]); return
        if self.path.startswith("/api/log/"):
            identifier = Path(self.path.removeprefix("/api/log/")).name
            match = next((p for p in run_directories() if p.name == identifier), None)
            self.send_json({"log": tail(match / "benchmark.log") if match else "Run not found."}, 200 if match else 404); return
        self.send_json({"error": "Not found"}, 404)

    def do_POST(self) -> None:
        if self.path != "/api/start": self.send_json({"error": "Not found"}, 404); return
        try:
            length = int(self.headers.get("Content-Length", "0")); payload = json.loads(self.rfile.read(length))
            models = {str(m) for m in payload["models"]}; suites = [str(s) for s in payload["suites"]]
            if not models or not suites or any(s not in SUITES for s in suites): raise ValueError("Select valid models and suites.")
            known = {str(row.get("model")) for row in load_catalog()}
            if not models <= known: raise ValueError("Unknown model selection.")
            profile = str(payload.get("profile", "standard"))
            if profile not in {"quick", "standard", "full"}: raise ValueError("Invalid profile.")
            config = selected_catalog(models); log = results_root() / "ui-launch.log"; log.parent.mkdir(parents=True, exist_ok=True)
            env = {**os.environ, "BENCH_MODELS_CONFIG": str(config)}
            with log.open("ab") as output:
                subprocess.Popen([str(ROOT / "benchmark"), "start", *suites, "--profile", profile], cwd=ROOT, env=env, stdin=subprocess.DEVNULL, stdout=output, stderr=subprocess.STDOUT, start_new_session=True)
            self.send_json({"message": "Preflight started. Refresh the Runs list in a moment."}, HTTPStatus.ACCEPTED)
        except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
            self.send_json({"error": str(exc)}, 400)

    def log_message(self, format: str, *args: Any) -> None: pass


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the AI Benchmark control panel.")
    parser.add_argument("--host", default="0.0.0.0", help="Network interface to listen on (default: all interfaces)")
    parser.add_argument("--port", default=8080, type=int, help="TCP port (default: 8080)")
    args = parser.parse_args()
    server = ThreadingHTTPServer((args.host, args.port), App)
    print(f"AI Benchmark web UI: http://{args.host}:{args.port}", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
