#!/usr/bin/env python3
"""Small LAN control panel for the AI Benchmark command line runner."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import signal
import socket
import subprocess
import sys
import threading
import tomllib
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SUITES = ("core", "coding-agent", "rag", "vision", "image", "speech", "music", "web")


def results_root() -> Path:
    configured = os.environ.get("BENCH_RESULTS_DIR")
    if configured:
        return Path(configured).expanduser()
    return Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local")) / "ai-benchmark"


def load_catalog() -> list[dict[str, Any]]:
    return tomllib.loads((ROOT / "config/models.toml").read_text(encoding="utf-8")).get("models", [])


def latest_scan(*, refresh: bool = False) -> dict[str, Any]:
    root = results_root()
    scans = sorted((root / "scans").glob("*/latest.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    if scans and not refresh:
        return json_file(scans[0], {})
    machine = socket.gethostname().split(".", 1)[0]
    output_dir = root / "scans" / machine
    output_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [sys.executable, str(ROOT / "scripts/scan_machine.py"), "--models", str(ROOT / "config/models.toml"),
         "--output", str(output_dir / "latest.json"), "--eligible-config", str(output_dir / "eligible.models.tsv")],
        check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True, timeout=30,
    )
    return json_file(output_dir / "latest.json", {})


def installed_models(scan: dict[str, Any]) -> dict[str, bool]:
    """Read local model/cache state without downloading or contacting remote services."""
    present: set[str] = set()
    if shutil.which("ollama"):
        try:
            output = subprocess.check_output(["ollama", "list"], text=True, stderr=subprocess.DEVNULL, timeout=5)
            for line in output.splitlines()[1:]:
                columns = line.split()
                if columns:
                    present.add(columns[0])
        except (OSError, subprocess.SubprocessError):
            pass
    storage = (scan.get("ollama_models_storage") or {}).get("path", "~/.ollama/models")
    cache = Path(os.environ.get("BENCH_CACHE_DIR") or Path(storage) / "benchmark-cache")
    for manifest in [*cache.glob("image/models/*.json"), cache / "music/prepared.json"]:
        for row in json_file(manifest, {}).get("models", []):
            if row.get("model") and row.get("local_path") and Path(row["local_path"]).exists():
                present.add(str(row["model"]))
    speech = json_file(cache / "speech/prepared.json", {})
    for model, path in (speech.get("whisper_cpp", {}).get("models", {}) or {}).items():
        if Path(path).exists():
            present.add(str(model))
    for model, assets in (speech.get("tts_assets", {}) or {}).items():
        if isinstance(assets, dict) and assets.get("onnx") and Path(assets["onnx"]).exists():
            present.add(str(model))
    return {str(row.get("model")): str(row.get("model")) in present or f"{row.get('model')}:latest" in present for row in load_catalog()}


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return str(value)


def selected_catalog(models: set[str]) -> Path:
    destination = results_root() / "ui-selections" / f"models-{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}.toml"
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Per-run selection generated by the benchmark web interface.", ""]
    for row in load_catalog():
        lines.append("[[models]]")
        for key, value in row.items():
            if key == "enabled":
                value = bool(value) and row.get("model") in models
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def precheck_path(identifier: str) -> Path:
    return results_root() / "ui-prechecks" / f"{identifier}.json"


def reconcile_precheck(record: dict[str, Any]) -> dict[str, Any]:
    if record.get("status") in {"running", "stopping"}:
        if not record.get("pid"):
            record.update({"status": "cancelled", "finished_at": datetime.now(timezone.utc).isoformat(timespec="seconds")})
        else:
            try:
                os.kill(int(record["pid"]), 0)
            except ProcessLookupError:
                record.update({"status": "cancelled", "finished_at": datetime.now(timezone.utc).isoformat(timespec="seconds")})
    return record


def finish_precheck(record_path: Path, command: list[str], env: dict[str, str]) -> None:
    record = json_file(record_path, {})
    with Path(record["log"]).open("ab") as output:
        process = subprocess.Popen(command, cwd=ROOT, env=env, stdin=subprocess.DEVNULL, stdout=output, stderr=subprocess.STDOUT, start_new_session=True)
        record["pid"] = process.pid
        write_json(record_path, record)
        exit_code = process.wait()
    record = json_file(record_path, record)
    status = "cancelled" if record.get("status") == "stopping" else "passed" if exit_code == 0 else "failed"
    record.update({"status": status, "exit_code": exit_code, "finished_at": datetime.now(timezone.utc).isoformat(timespec="seconds")})
    write_json(record_path, record)


def json_file(path: Path, fallback: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return fallback


def run_directories() -> list[Path]:
    root = results_root() / "runs"
    return sorted((p for p in root.glob("*/*") if (p / "state.json").is_file()), key=lambda p: p.stat().st_mtime, reverse=True)


def run_summary(directory: Path) -> dict[str, Any]:
    state = json_file(directory / "state.json", {})
    return {"id": directory.name, "machine": directory.parent.name, "state": state}


def tail(path: Path, size: int | None = None, *, compact_ollama: bool = False) -> str:
    try:
        with path.open("rb") as handle:
            if size is not None:
                handle.seek(0, 2)
                handle.seek(max(0, handle.tell() - size))
            text = handle.read().decode("utf-8", errors="replace")
            # Progress bars use terminal cursor controls. They are useful in a terminal but not in a browser log.
            text = re.sub(r"\x1b(?:\[[0-?]*[ -/]*[@-~]|\][^\x07]*(?:\x07|\x1b\\))", "", text).replace("\r", "\n")
            if not compact_ollama:
                return text
            clean: list[str] = []
            for line in text.splitlines():
                marker = re.match(r"@@PRECHECK\|model-[^|]+\|Downloading ([^|]+)\|(running|done)", line)
                if marker:
                    clean.append(f"Downloading {marker.group(1)}" + (" completed." if marker.group(2) == "done" else "…"))
                    continue
                # Ollama rewrites these lines many times per second. The overview already presents their progress.
                if "pulling manifest" in line or re.search(r"pulling [0-9a-f]{8,}:", line, re.I):
                    continue
                clean.append(line)
            return "\n".join(clean)
    except OSError:
        return "No log is available yet."


PAGE = r"""<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Benchmark</title><style>
body{margin:0;padding:26px;background:#101827;color:#e6edf7;font:16px system-ui,sans-serif}h1{margin:0;font-size:30px}.intro,.muted{color:#aebbd1}.app{display:grid;grid-template-columns:minmax(0,2.2fr) minmax(360px,1fr);gap:20px;align-items:start}section{background:#182235;border:1px solid #2c3b55;border-radius:12px;padding:22px;margin:18px 0}.app section:first-child{margin-top:0}h2{margin:0 0 16px}h3{margin:24px 0 10px}.metrics{display:grid;grid-template-columns:repeat(5,minmax(150px,1fr));gap:10px}.metric{background:#101827;border:1px solid #2c3b55;border-radius:8px;padding:12px}.metric b{display:block;font-size:18px;margin-top:3px}.metric small{display:block;color:#aebbd1;margin-top:5px}.space-green{color:#52c78b}.space-orange{color:#ffb454}.space-red{color:#ff6b6b}.suite-title,.overview-title{display:flex;align-items:center;justify-content:space-between}.badge{border-radius:999px;padding:5px 9px;font-size:12px;font-weight:700;background:#293956;color:#e6edf7}.badge-running{background:#4b371e;color:#ffb454}.badge-passed{background:#173b2b;color:#52c78b}.badge-failed{background:#47232b;color:#ff9292}.suite-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.suite-grid label{background:#101827;border:1px solid #2c3b55;border-radius:7px;padding:10px;cursor:pointer}.suite-grid b{display:block}.suite-grid small{display:block;color:#aebbd1;margin-left:23px;margin-top:2px}.models{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.model{background:#101827;border:1px solid #2c3b55;border-radius:7px;padding:10px}.model-head{display:flex;justify-content:space-between;gap:8px}.model strong{display:block}.tag{color:#9fddb9;font-size:13px}.installed{color:#52c78b;font-size:12px;font-weight:700;white-space:nowrap}.missing{color:#ff6b6b;font-size:12px;font-weight:700;white-space:nowrap}button{background:#52c78b;border:0;border-radius:6px;padding:10px 14px;font-weight:700;cursor:pointer}.secondary{background:#293956;color:#e6edf7}button:disabled{opacity:.45;cursor:not-allowed}pre{background:#0b1220;padding:12px;overflow:auto;max-height:42vh;white-space:pre-wrap}#message{font-weight:600}.precheck{border-left:3px solid #ffb454;background:#101827;padding:11px;margin:14px 0}.passed{border-color:#52c78b}.failed{border-color:#ff6b6b}.total{background:#101827;border:1px solid #2c3b55;border-radius:8px;padding:12px;margin-bottom:18px}.total b{font-size:18px}.total progress{width:100%;height:10px;accent-color:#52c78b}.step{margin:14px 0}.step-head{display:flex;justify-content:space-between;gap:10px;font-size:14px}.step-detail{display:block;color:#aebbd1;font-size:12px;margin:3px 0 6px}.substep{margin:8px 0 0 14px;padding-left:10px;border-left:2px solid #2c3b55}.step-done{color:#52c78b}.step-running{color:#ffb454}.step progress{width:100%;height:8px;accent-color:#52c78b}.step-running progress{accent-color:#ffb454}@media(max-width:900px){.app{grid-template-columns:1fr}.metrics,.suite-grid,.models{grid-template-columns:repeat(2,1fr)}}</style>
<style>
body{--cpu-glow:.08;--ram-glow:.08;--vram-glow:.03;background:radial-gradient(circle at 14% 10%,rgba(82,199,139,var(--cpu-glow)),transparent 27%),radial-gradient(circle at 73% 8%,rgba(91,141,239,var(--ram-glow)),transparent 26%),radial-gradient(circle at 92% 80%,rgba(255,180,84,var(--vram-glow)),transparent 30%),#101827}
body::before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.28;background-image:radial-gradient(circle at 12% 18%,#52c78b 0 1px,transparent 2px),radial-gradient(circle at 68% 22%,#6d9cff 0 1px,transparent 2px),radial-gradient(circle at 34% 77%,#52c78b 0 1px,transparent 2px),linear-gradient(27deg,transparent 49.7%,rgba(82,199,139,.18) 50%,transparent 50.3%),linear-gradient(153deg,transparent 49.7%,rgba(109,156,255,.12) 50%,transparent 50.3%);background-size:190px 170px,230px 210px,260px 240px,210px 180px,260px 220px;mask-image:linear-gradient(to bottom,black,transparent 88%)}
h1,.app{position:relative;z-index:1}.metric{box-shadow:inset 0 1px 0 rgba(130,181,255,.08),0 8px 26px rgba(4,10,22,.14)}.metric:hover{border-color:#45638d;box-shadow:0 0 20px rgba(82,199,139,.12)}
@media(prefers-reduced-motion:reduce){body::before{display:none}}
#neural-core{display:block;width:100%;height:176px;border:1px solid #3d668f;border-radius:9px;background:#070e1b;box-shadow:inset 0 0 40px rgba(82,199,139,.18),0 0 26px rgba(82,199,139,.1)}.neural-panel{display:flex;flex-direction:column;min-height:0}.neural-panel h2{margin-bottom:12px}.overview-tools{display:flex;align-items:center;gap:10px}.overview-title h2{margin:0}
@media(max-width:900px){.side-top{grid-template-columns:1fr}.neural-panel{display:none}}
.models{grid-template-columns:repeat(4,1fr)}
@media(min-width:901px){
body{height:100vh;box-sizing:border-box;overflow:hidden}
.app{height:calc(100vh - 52px)}
.app>section{height:100%;box-sizing:border-box;display:flex;flex-direction:column;overflow:hidden}
#models{flex:1;min-height:0;overflow:auto;padding-right:5px}
#models,aside pre{scrollbar-width:none;-ms-overflow-style:none}
#models::-webkit-scrollbar,aside pre::-webkit-scrollbar{display:none}
.actions{display:flex;justify-content:center;align-items:center;gap:10px;flex-wrap:wrap}
aside{height:100%;display:grid;grid-template-rows:auto minmax(0,1fr);gap:18px;overflow:hidden}.side-top{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(240px,.85fr);gap:18px;align-items:stretch}.side-top section,aside>section{margin:0;box-sizing:border-box}.side-top section:last-child,aside>section:last-child{display:flex;flex-direction:column;min-height:0}aside pre{flex:1;min-height:0;max-height:none;margin:0}
}
</style>
<main class="app"><section><h2>Start a run</h2><div id="machine" class="metrics">Loading machine scan…</div><div class="suite-title"><h3>Suites</h3><button id="select-all" class="secondary" type="button">Select all suites</button></div><div id="suites" class="suite-grid"></div><h3>Approved models</h3><p id="model-summary" class="muted">Loading…</p><div id="models" class="models"></div><p>Profile: <select id="profile"><option value="quick">Quick</option><option value="standard" selected>Standard</option><option value="full">Full</option></select></p><div id="precheck-report" class="precheck">Run the precheck before starting a benchmark.</div><div class="actions"><button id="precheck">Run precheck</button><button id="stop-precheck" class="secondary" disabled>Stop precheck</button><button id="start" disabled>Start benchmark</button></div><span id="message"></span></section>
<aside><div class="side-top"><section><div class="overview-title"><h2>Precheck overview</h2><div class="overview-tools"><span id="precheck-status" class="badge">Not run</span></div></div><div id="precheck-steps" class="muted">Run a precheck to see its progress.</div></section><section class="neural-panel"><h2>Neural activity</h2><canvas id="neural-core" width="640" height="180" aria-label="Live neural feedback"></canvas></section></div><section><h2>Technical log</h2><pre id="log">Select a precheck to view its log.</pre></section></aside></main>
<script>
let catalog=[],scan={},installed={},precheck=null,followLog=true; const suiteLabels={core:['Algemene taalmodellen','Tekst, kennis en instructies'], 'coding-agent':['Code & agents','Programmeren en zelfstandige taken'],rag:['Documenten & RAG','Zoeken en antwoorden uit documenten'],vision:['Beeld & schermen','Afbeeldingen en schermafbeeldingen'],image:['Afbeeldingen maken','Tekst-naar-afbeelding'],speech:['Spraak & audio','Spraakherkenning en spraaksynthese'],music:['Muziek maken','Tekst- en melodie-naar-muziek'],web:['Webonderzoek','Zoeken, bronnen en citaten']}; const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function get(url){let r=await fetch(url);if(!r.ok)throw Error(await r.text());return r.json()}
function setLog(text){let log=document.querySelector('#log');log.textContent=text;updatePrecheckBadge();if(followLog)log.scrollTop=log.scrollHeight}
document.querySelector('#log').addEventListener('scroll',e=>{let log=e.currentTarget;followLog=log.scrollTop+log.clientHeight>=log.scrollHeight-24})
function renderPrecheckSteps(output){let events=new Map;for(let line of output.split('\n')){if(!line.startsWith('@@PRECHECK|'))continue;let [,id,label,status]=line.split('|');events.set(id,{label,status})}let target=document.querySelector('#precheck-steps'),rows=[];function row(label,detail,value,done,substep=''){let percent=Math.max(0,Math.min(100,Math.round(value)));rows.push(`<div class="step ${done?'step-done':'step-running'}"><div class="step-head"><span>${esc(label)}</span><span>${done?'Complete':percent+'%'}</span></div><span class="step-detail">${esc(detail)}</span><progress value="${percent}" max="100"></progress>${substep}</div>`)}let system=events.get('environment'),systemValue=system?.status==='done'?100:0;if(system)row('System readiness','Checking disk space, required tools and the Ollama service.',systemValue,system.status==='done');let suites=(precheck?.suites||[]).map(s=>({id:'suite-'+s,name:(suiteLabels[s]||[s])[0]})),completedSuites=suites.filter(s=>events.get(s.id)?.status==='done').length,activeSuite=suites.find(s=>events.get(s.id)?.status==='running'),suiteValue=suites.length?completedSuites/suites.length*100:0;if(suites.length)row('Preparing benchmark suites',activeSuite?`${completedSuites} of ${suites.length} complete. Now preparing ${activeSuite.name}.`:completedSuites===suites.length?'All selected suites are ready.':`${completedSuites} of ${suites.length} suites prepared.`,suiteValue,completedSuites===suites.length);let models=(precheck?.models||[]).filter(m=>catalog.find(c=>c.model===m)?.backend==='ollama'),modelEvents=models.map(m=>({model:m,event:events.get('model-'+m)})),completedModels=modelEvents.filter(x=>x.event?.status==='done').length,activeModel=modelEvents.find(x=>x.event?.status==='running'),progressMatches=[...output.matchAll(/pulling\s+[^:\s]+:\s+(\d+)%/g)],downloadPercent=progressMatches.length?Number(progressMatches.at(-1)[1]):0,modelValue=models.length?(completedModels+(activeModel?downloadPercent/100:0))/models.length*100:0;if(models.length){let detail=completedModels===models.length?'All selected Ollama models are ready.':`${completedModels} of ${models.length} model downloads complete.`,substep=activeModel?`<div class="substep step-running"><div class="step-head"><span>${esc('Downloading '+activeModel.model)}</span><span>${downloadPercent}%</span></div><progress value="${downloadPercent}" max="100"></progress></div>`:'';row('Downloading Ollama models',detail,modelValue,completedModels===models.length,substep)}if(!rows.length){target.className='muted';target.textContent='Waiting for precheck progress…';return}let parts=[];if(system)parts.push([systemValue,10]);if(suites.length)parts.push([suiteValue,30]);if(models.length)parts.push([modelValue,60]);let total=Math.round(parts.reduce((sum,p)=>sum+p[0]*p[1],0)/parts.reduce((sum,p)=>sum+p[1],0));target.className='';target.innerHTML=`<div class="total"><div class="step-head"><b>Total precheck progress</b><b>${total}%</b></div><progress value="${total}" max="100"></progress></div>`+rows.join('')}
const renderPrecheckOverview=renderPrecheckSteps;
renderPrecheckSteps=output=>renderPrecheckOverview(String(precheck?.raw_output||output).replace(/^.*?(@@PRECHECK\|)/gm,'$1'));
function selectedSuites(){return [...document.querySelectorAll('input[name="suite"]:checked')].map(x=>x.value)}
function approvedModels(){let selected=new Set(selectedSuites()),approved=new Map((scan.models||[]).filter(x=>x.allowed).map(x=>[x.model,x]));return catalog.filter(m=>approved.has(m.model)&&m.suites.some(s=>selected.has(s))).map(m=>({...m,scan:approved.get(m.model)})).sort((a,b)=>a.model.localeCompare(b.model))}
function renderModels(){let models=approvedModels();document.querySelector('#model-summary').textContent=models.length?`${models.length} model(s) approved by this machine scan will be used for the selected suite(s).`:'No scan-approved models support the selected suite(s).';document.querySelector('#models').innerHTML=models.map(m=>{let ready=installed[m.model],label=ready?'Installed':'Not installed',r=m.scan.requirements;return `<div class="model"><div class="model-head"><strong>${esc(m.model)}</strong><span class="${ready?'installed':'missing'}">${label}</span></div><span class="tag">Required: ${r.ram_gib} GiB RAM · ${r.vram_gib} GiB VRAM · ${r.free_disk_gib} GiB disk</span></div>`}).join('')}
function updatePrecheckBadge(){let status=precheck?.status||'missing',labels={missing:'Not run',running:'Running',stopping:'Stopping',passed:'Passed',failed:'Failed',cancelled:'Stopped'},badge=document.querySelector('#precheck-status');badge.textContent=labels[status]||status;badge.className='badge '+(status==='passed'?'badge-passed':status==='running'||status==='stopping'?'badge-running':status==='failed'||status==='cancelled'?'badge-failed':'')}
function invalidatePrecheck(){precheck=null;updatePrecheckBadge();document.querySelector('#start').disabled=true;document.querySelector('#stop-precheck').disabled=true;document.querySelector('#precheck-report').className='precheck';document.querySelector('#precheck-report').textContent='Run the precheck before starting a benchmark.'}
function precheckPayload(){return {models:approvedModels().map(m=>m.model),suites:selectedSuites(),profile:document.querySelector('#profile').value}}
function saveSelection(){localStorage.setItem('ai-benchmark-selection',JSON.stringify({suites:selectedSuites(),profile:document.querySelector('#profile').value}))}
function allSelectedModelsInstalled(){return approvedModels().every(m=>installed[m.model])}
async function refreshPrecheck(){if(!precheck)return;let d=await get('/api/precheck/'+precheck.id);precheck=d;let report=document.querySelector('#precheck-report');report.className='precheck '+(d.status==='passed'?'passed':d.status==='failed'||d.status==='cancelled'?'failed':'');report.textContent=d.status==='running'?'Precheck is running. Dependencies, cache and model downloads are being prepared…':d.status==='stopping'?'Stopping the precheck and its downloads…':d.status==='passed'?'Precheck passed. You can start this exact benchmark selection.':d.status==='cancelled'?'Precheck stopped. You can adjust the selection and run it again.':`Precheck failed (exit code ${d.exit_code}). Check the log below.`;setLog(d.output||'');renderPrecheckSteps(d.output||'');if(d.status==='passed'){let overview=await get('/api/overview');installed=overview.installed||{};renderModels()}document.querySelector('#start').disabled=d.status!=='passed'||!allSelectedModelsInstalled();document.querySelector('#precheck').disabled=d.status==='running'||d.status==='stopping';document.querySelector('#stop-precheck').disabled=d.status!=='running'||!d.pid;if(d.status==='running'||d.status==='stopping')setTimeout(refreshPrecheck,2500)}
async function restorePrecheck(){let response=await fetch('/api/precheck-status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(precheckPayload())});if(!response.ok)return;let record=await response.json();if(record.status!=='missing'){precheck=record;await refreshPrecheck()}}
function diskMetric(label,disk){let free=Number(disk.free_gib),total=Number(disk.total_gib),used=Number(disk.used_gib),percent=total?Math.round(free/total*100):0,colour=percent<15?'space-red':percent<30?'space-orange':'space-green';return `<div class="metric"><span class="muted">${label}</span><b class="${colour}">${percent}% free</b><small>${free.toFixed(2)} GiB free / ${total.toFixed(2)} GiB total (${used.toFixed(2)} GiB used)</small></div>`}
function memoryMetric(label,free,total){if(!total)return `<div class="metric"><span class="muted">${label}</span><b>0 GiB</b><small>No GPU is reported.</small></div>`;let used=total-free,percent=Math.round(free/total*100),colour=percent<15?'space-red':percent<30?'space-orange':'space-green';return `<div class="metric"><span class="muted">${label}</span><b class="${colour}">${percent}% free</b><small>${free.toFixed(2)} GiB free / ${total.toFixed(2)} GiB total (${used.toFixed(2)} GiB used)</small></div>`}
function renderMetrics(){let store=scan.ollama_models_storage||{},root=scan.root_storage||{},same=scan.ollama_models_on_root_filesystem,load=Number(scan.cpu_load_percent),cpuColour=load>85?'space-red':load>60?'space-orange':'space-green',cpu=`<div class="metric"><span class="muted">CPU (1 min load)</span><b class="${cpuColour}">${Number.isFinite(load)?load.toFixed(0):'?'}%</b><small>${esc(scan.cpu||'Unknown CPU')} · ${scan.cpu_count??'?'} logical cores</small></div>`,ram=memoryMetric('Available RAM',Number(scan.available_ram_gib),Number(scan.total_ram_gib)),vram=memoryMetric('Free VRAM',Number(scan.available_vram_gib||0),Number(scan.total_vram_gib||0)),disks=same?diskMetric('Root & Ollama disk',store):diskMetric('Root disk',root)+diskMetric('Ollama disk',store);document.querySelector('#machine').innerHTML=cpu+ram+vram+disks}
const renderResourceCards=renderMetrics;
renderMetrics=()=>{renderResourceCards();let cpu=Math.max(0,Math.min(100,Number(scan.cpu_load_percent)||0)),ramTotal=Number(scan.total_ram_gib)||0,ramFree=Number(scan.available_ram_gib)||0,vramTotal=Number(scan.total_vram_gib)||0,vramFree=Number(scan.available_vram_gib)||0,style=document.documentElement.style;style.setProperty('--cpu-glow',(0.035+cpu/100*0.13).toFixed(3));style.setProperty('--ram-glow',(0.025+(ramTotal?1-ramFree/ramTotal:0)*0.12).toFixed(3));style.setProperty('--vram-glow',(0.015+(vramTotal?1-vramFree/vramTotal:0)*0.16).toFixed(3))}
async function refreshResources(){try{let d=await get('/api/resources');scan=d.scan||scan;installed=d.installed||installed;renderMetrics();renderModels()}catch(_){}}
async function load(){let d=await get('/api/overview');catalog=d.catalog;scan=d.scan||{};installed=d.installed||{};renderMetrics();
document.querySelector('#suites').innerHTML=d.suites.map((s,i)=>{let label=suiteLabels[s]||[s,''];return `<label><input type="checkbox" name="suite" value="${s}" ${i===0?'checked':''}><b>${label[0]}</b><small>${label[1]}</small></label>`}).join('');try{let saved=JSON.parse(localStorage.getItem('ai-benchmark-selection')||'{}');if(Array.isArray(saved.suites)){document.querySelectorAll('input[name="suite"]').forEach(x=>x.checked=saved.suites.includes(x.value))}if(['quick','standard','full'].includes(saved.profile))document.querySelector('#profile').value=saved.profile}catch(_){}document.querySelectorAll('input[name="suite"]').forEach(x=>x.onchange=()=>{invalidatePrecheck();saveSelection();renderModels()});document.querySelector('#select-all').onclick=()=>{document.querySelectorAll('input[name="suite"]').forEach(x=>x.checked=true);invalidatePrecheck();saveSelection();renderModels()};document.querySelector('#profile').onchange=()=>{invalidatePrecheck();saveSelection()};renderModels();await restorePrecheck()}
async function runs(){let d=await get('/api/runs');document.querySelector('#runs').innerHTML=d.length?d.map(r=>{let p=r.state.progress||{},active=['starting','running','resuming'].includes(r.state.status);return `<p><button onclick="showLog('${r.id}')">Log</button>${active?` <button class="secondary" onclick="stopRun('${r.id}')">Stop benchmark</button>`:''}<br><b>${esc(r.id)}</b> — ${esc(r.state.status||'unknown')} — ${p.completed||0}/${p.total||0} (${p.percent||0}%)</p>`}).join(''):'No runs yet.'}
async function stopRun(id){if(!confirm(`Stop benchmark ${id}? The current model call may finish first.`))return;let r=await fetch('/api/stop-run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id})}),d=await r.json();if(!r.ok)alert(d.error);else{document.querySelector('#message').textContent=d.message;runs()}}
async function showLog(id){setLog((await get('/api/log/'+encodeURIComponent(id))).log)}
document.querySelector('#precheck').onclick=async()=>{let payload=precheckPayload(),message=document.querySelector('#message');if(!payload.models.length||!payload.suites.length){message.textContent='Choose a suite with at least one scan-approved model.';return}message.textContent='Starting precheck…';try{let r=await fetch('/api/precheck',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});let d=await r.json();if(!r.ok)throw Error(d.error);precheck=d;message.textContent='';refreshPrecheck()}catch(e){message.textContent=e.message}}
document.querySelector('#stop-precheck').onclick=async()=>{if(!precheck)return;document.querySelector('#stop-precheck').disabled=true;await fetch('/api/precheck-stop',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:precheck.id})});refreshPrecheck()}
document.querySelector('#start').onclick=async()=>{let payload=precheckPayload(),message=document.querySelector('#message');if(!precheck||precheck.status!=='passed')return;if(!confirm(`Start ${payload.suites.join(', ')} with all ${payload.models.length} approved model(s)?`))return;message.textContent='Starting benchmark…';try{let r=await fetch('/api/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,precheck_id:precheck.id})});let d=await r.json();if(!r.ok)throw Error(d.error);message.textContent=d.message}catch(e){message.textContent=e.message}}
const neuralCanvas=document.querySelector('#neural-core'),neuralContext=neuralCanvas.getContext('2d'),neuralPoints=Array.from({length:18},(_,i)=>{let a=i*2.399,z=((i*37)%100)/50-1,r=Math.sqrt(1-z*z);return [Math.cos(a)*r,Math.sin(a)*r,z]}),neuralEdges=neuralPoints.flatMap((_,i)=>[[i,(i+1)%18],[i,(i+5)%18]]);
function drawNeuralCore(time=0){let c=neuralContext,w=640,h=180,raw=Math.max(Number(scan.cpu_load_percent)||0,100-(Number(scan.total_ram_gib)?Number(scan.available_ram_gib)/Number(scan.total_ram_gib)*100:100),Number(scan.total_vram_gib)?100-Number(scan.available_vram_gib)/Number(scan.total_vram_gib)*100:0)/100,speed=.24+raw*1.9,angle=time/1000*speed,scale=68+raw*29,project=([x,y,z])=>{let rx=x*Math.cos(angle)-z*Math.sin(angle),rz=x*Math.sin(angle)+z*Math.cos(angle),ry=y*Math.cos(angle*.63)-rz*Math.sin(angle*.63);rz=y*Math.sin(angle*.63)+rz*Math.cos(angle*.63);let d=3.4+rz;return [w/2+rx*scale/d,h/2+ry*scale/d,rz]},nodes=neuralPoints.map(project);c.clearRect(0,0,w,h);c.fillStyle='#070e1b';c.fillRect(0,0,w,h);let aura=c.createRadialGradient(w/2,h/2,5,w/2,h/2,Math.max(w,h)*.6);aura.addColorStop(0,`rgba(19,105,74,${.22+raw*.18})`);aura.addColorStop(1,'rgba(7,14,27,0)');c.fillStyle=aura;c.fillRect(0,0,w,h);neuralEdges.forEach(([a,b],i)=>{let p=nodes[a],q=nodes[b],t=(time/1000*speed+i*.071)%1,x=p[0]+(q[0]-p[0])*t,y=p[1]+(q[1]-p[1])*t;c.strokeStyle=`rgba(82,199,139,${.12+raw*.45})`;c.lineWidth=1.2;c.beginPath();c.moveTo(p[0],p[1]);c.lineTo(q[0],q[1]);c.stroke();let g=c.createRadialGradient(x,y,0,x,y,5+raw*8);g.addColorStop(0,'#e2fff0');g.addColorStop(.3,'#52c78b');g.addColorStop(1,'rgba(82,199,139,0)');c.fillStyle=g;c.beginPath();c.arc(x,y,5+raw*8,0,Math.PI*2);c.fill()});nodes.sort((a,b)=>a[2]-b[2]).forEach(([x,y,z],i)=>{let r=2.4+(z+1)*1.8+raw*2.3,pulse=(Math.sin(time/(430-raw*230)+i)+1)/2,g=c.createRadialGradient(x,y,0,x,y,r*(3+pulse));g.addColorStop(0,'#effff6');g.addColorStop(.22,'#52c78b');g.addColorStop(1,'rgba(82,199,139,0)');c.fillStyle=g;c.beginPath();c.arc(x,y,r*(3+pulse),0,Math.PI*2);c.fill()});c.fillStyle='#caffe1';c.font='600 12px system-ui';c.fillText(`3D NEURAL ACTIVITY  ·  ${Math.round(raw*100)}% LOAD`,18,h-16);requestAnimationFrame(drawNeuralCore)}
requestAnimationFrame(drawNeuralCore);load().catch(e=>document.body.insertAdjacentHTML('beforeend','<pre>'+esc(e.message)+'</pre>'));setInterval(refreshResources,10000)
</script></html>"""


class App(BaseHTTPRequestHandler):
    server_version = "AIBenchmarkUI/1.0"

    def send_json(self, data: Any, status: int = 200) -> None:
        encoded = json.dumps(data).encode("utf-8")
        self.send_response(status); self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded))); self.end_headers(); self.wfile.write(encoded)

    def do_GET(self) -> None:
        if self.path == "/":
            encoded = PAGE.encode("utf-8"); self.send_response(200); self.send_header("Content-Type", "text/html; charset=utf-8"); self.send_header("Content-Length", str(len(encoded))); self.end_headers(); self.wfile.write(encoded); return
        if self.path == "/api/overview":
            try:
                scan = latest_scan()
            except (OSError, subprocess.SubprocessError) as exc:
                self.send_json({"error": f"Machine scan failed: {exc}"}, 500); return
            self.send_json({"catalog": load_catalog(), "suites": SUITES, "scan": scan, "installed": installed_models(scan)}); return
        if self.path == "/api/resources":
            try:
                scan = latest_scan(refresh=True)
            except (OSError, subprocess.SubprocessError) as exc:
                self.send_json({"error": f"Resource refresh failed: {exc}"}, 500); return
            self.send_json({"scan": scan, "installed": installed_models(scan)}); return
        if self.path == "/api/runs": self.send_json([run_summary(p) for p in run_directories()[:30]]); return
        if self.path.startswith("/api/precheck/"):
            identifier = Path(self.path.removeprefix("/api/precheck/")).name
            record = json_file(precheck_path(identifier), None)
            if record:
                record = reconcile_precheck(record)
                write_json(precheck_path(identifier), record)
                record["raw_output"] = tail(Path(record["log"]))
                record["output"] = tail(Path(record["log"]), compact_ollama=True)
            self.send_json(record if record else {"error": "Precheck not found"}, 200 if record else 404); return
        if self.path.startswith("/api/log/"):
            identifier = Path(self.path.removeprefix("/api/log/")).name
            match = next((p for p in run_directories() if p.name == identifier), None)
            self.send_json({"log": tail(match / "benchmark.log") if match else "Run not found."}, 200 if match else 404); return
        self.send_json({"error": "Not found"}, 404)

    def do_POST(self) -> None:
        if self.path not in {"/api/start", "/api/precheck", "/api/precheck-status", "/api/precheck-stop", "/api/stop-run"}: self.send_json({"error": "Not found"}, 404); return
        try:
            length = int(self.headers.get("Content-Length", "0")); payload = json.loads(self.rfile.read(length))
            if self.path == "/api/stop-run":
                identifier = Path(str(payload.get("id", ""))).name
                run = next((directory for directory in run_directories() if directory.name == identifier), None)
                if not run:
                    raise ValueError("Run not found.")
                (run / "stop.requested").touch()
                self.send_json({"message": f"Graceful stop requested for {identifier}."}, HTTPStatus.ACCEPTED); return
            if self.path == "/api/precheck-stop":
                identifier = Path(str(payload.get("id", ""))).name
                record_path = precheck_path(identifier)
                record = json_file(record_path, {})
                if record.get("status") != "running" or not record.get("pid"):
                    raise ValueError("No active precheck can be stopped.")
                try:
                    os.killpg(int(record["pid"]), signal.SIGTERM)
                except ProcessLookupError:
                    pass
                record["status"] = "stopping"
                record["stop_requested_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
                write_json(record_path, record)
                self.send_json(record, HTTPStatus.ACCEPTED); return
            models = {str(m) for m in payload["models"]}; suites = [str(s) for s in payload["suites"]]
            if not models or not suites or any(s not in SUITES for s in suites): raise ValueError("Select valid models and suites.")
            known = {str(row.get("model")) for row in load_catalog()}
            if not models <= known: raise ValueError("Unknown model selection.")
            profile = str(payload.get("profile", "standard"))
            if profile not in {"quick", "standard", "full"}: raise ValueError("Invalid profile.")
            identity = json.dumps({"models": sorted(models), "suites": suites, "profile": profile}, separators=(",", ":"))
            identifier = hashlib.sha256(identity.encode("utf-8")).hexdigest()[:16]
            if self.path == "/api/precheck-status":
                record = json_file(precheck_path(identifier), {"status": "missing"})
                if record.get("log"):
                    record = reconcile_precheck(record)
                    write_json(precheck_path(identifier), record)
                    record["raw_output"] = tail(Path(record["log"]))
                    record["output"] = tail(Path(record["log"]), compact_ollama=True)
                self.send_json(record); return
            if self.path == "/api/precheck":
                record_path = precheck_path(identifier)
                existing = json_file(record_path, {})
                if existing.get("status") == "running":
                    self.send_json(existing, HTTPStatus.ACCEPTED); return
                config = selected_catalog(models)
                log = results_root() / "ui-prechecks" / f"{identifier}.log"
                log.parent.mkdir(parents=True, exist_ok=True)
                log.write_bytes(b"")
                record = {"id": identifier, "status": "running", "models": sorted(models), "suites": suites, "profile": profile, "config": str(config), "log": str(log), "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds")}
                write_json(record_path, record)
                env = {**os.environ, "BENCH_MODELS_CONFIG": str(config)}
                command = [str(ROOT / "scripts/precheck.sh"), ",".join(suites), str(config), "1" if "coding-agent" in suites else "0", profile]
                threading.Thread(target=finish_precheck, args=(record_path, command, env), daemon=True).start()
                self.send_json(record, HTTPStatus.ACCEPTED); return
            identifier = str(payload.get("precheck_id", ""))
            record = json_file(precheck_path(identifier), {})
            if record.get("status") != "passed": raise ValueError("Run the precheck successfully before starting a benchmark.")
            if record.get("models") != sorted(models) or record.get("suites") != suites or record.get("profile") != profile: raise ValueError("The selection changed after the precheck. Run it again.")
            config = Path(record["config"]); log = results_root() / "ui-launch.log"; log.parent.mkdir(parents=True, exist_ok=True)
            env = {**os.environ, "BENCH_MODELS_CONFIG": str(config)}
            with log.open("ab") as output:
                subprocess.Popen([str(ROOT / "benchmark"), "start", *suites, "--profile", profile], cwd=ROOT, env=env, stdin=subprocess.DEVNULL, stdout=output, stderr=subprocess.STDOUT, start_new_session=True)
            self.send_json({"message": "Preflight started. Refresh the Runs list in a moment."}, HTTPStatus.ACCEPTED)
        except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
            self.send_json({"error": str(exc)}, 400)

    def log_message(self, format: str, *args: Any) -> None: pass


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the AI Benchmark control panel.")
    parser.add_argument("--host", default="0.0.0.0", help="Network interface to listen on (default: all interfaces)")
    parser.add_argument("--port", default=8080, type=int, help="TCP port (default: 8080)")
    args = parser.parse_args()
    server = ThreadingHTTPServer((args.host, args.port), App)
    print(f"AI Benchmark web UI: http://{args.host}:{args.port}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nAI Benchmark web UI stopped.", flush=True)
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
